import ProjectSection from "../../components/ProjectSection";

export default function UstraaDetail() {
  return (
    <>
      <div className="project-header">
        <div className="project-header-title">
          <h1>Ustraa</h1>
          <p>
            A single-material packaging concept designed to reduce waste from
            plastic blade cartridges.
          </p>
        </div>
        <div className="project-meta-data">
          <div className="metadata-container">
            <h5 className="metadata-title">Role</h5>
            <h5 className="metadata-content">Individual Project</h5>
          </div>
          <div className="metadata-container">
            <h5 className="metadata-title">Date</h5>
            <h5 className="metadata-content">Nov 2019</h5>
          </div>
          <div className="metadata-container">
            <h5 className="metadata-title">Categories</h5>
            <div className="metadata-content-multiple">
              <h5 className="metadata-content">Packaging</h5>
              <h5 className="metadata-content">Graphics</h5>
              <h5 className="metadata-content">Printing</h5>
            </div>
          </div>
        </div>
      </div>
      <div className="project-introduction">
        <div className="project-content-container">
          <p>
            This project explores a <b>sustainable redesign</b> of traditional
            razor blade packaging with the goal of reducing waste generated by
            plastic blade cartridges. The concept rethinks how everyday grooming
            products can be packaged more responsibly without compromising
            usability or protection.
          </p>
          <p>
            The packaging is designed using a <b>single recyclable material</b>,
            eliminating the need for mixed plastics and complex separation
            processes. By focusing on material simplicity and efficient form,
            the design aims to improve recyclability while encouraging more
            environmentally conscious consumer habits.
          </p>
        </div>
        <img src="/images/ustraa_thumnail.jpg" alt="ustraa packaging" />
      </div>
      <ProjectSection sectionTitle="Project Brief">
        <div className="project-brief-content">
          <div className="project-content-container">
            <p>
              To redesign existing razor blade packaging in a way that enhances
              recyclability and reduces environmental impact by minimizing
              material complexity.
            </p>
            <p>
              A packaging concept that demonstrates how thoughtful material
              selection and form can significantly reduce packaging waste,
              showcasing a practical approach to sustainability in everyday
              consumer products.
            </p>
          </div>
          <div className="ustraa-grid">
            <img className="ustraa01" src="/images/ustraa01.jpg" />
            <div className="ustraa-packaging">
              <img className="ustraa-pack01" src="/images/ustraa_pack01.jpg" />
              <img className="ustraa-pack02" src="/images/ustraa_pack02.jpg" />
              <img className="ustraa-pack03" src="/images/ustraa_pack03.jpg" />
            </div>
            <img className="ustraa03" src="/images/ustraa02.jpg" />
            <img className="ustraa04" src="/images/ustraa03.jpg" />
          </div>
          <h1 className="project-end-quote">
            Sustainability begins with better choices, <br />
            not more materials.
          </h1>
        </div>
      </ProjectSection>
    </>
  );
}
